### PR TITLE
Updated gitignore

### PR DESCRIPTION
**Pull request by tvb**
Helps not to worry about committing 3rd party plugin english translations into core.

### CODE REVIEW

**Comment by tvb** [comment]
Have you though on how to provide the translation definitions for the plugins not in core anymore?
-- Perhaps we should add the definitions to the plugin README or include the definitions.PLUGIN.php file into the repo which the user then needs to move manually to the language directory.

**Comment by tobyzerner** [comment]
Including a definitions.PLUGIN.php file in each plugin could give the wrong impression that this file would actually be loaded by default. Maybe it would be better to put them in a file called DEFINITIONS.txt or something like this? Hmm...

**Comment by tobyzerner** [comment]
It could probably be left to the plugin author to decide. If there's only a few definitions, they could be chucked in README. Otherwise a separate file would be better.

**Comment by tvb** [comment]
What are you gonna do with the plugins developed by esoTalk?

**Comment by tvb** [comment]
Oh and don't forget to add them all to the http://esotalk.org/forum/conversations/plugins section so people can find them easily without having to browse through GitHub.

**Comment by tobyzerner** [comment]
Yep it's on my list. I'll probably put them in README

**Pull request merged**
