### PR TITLE
Hide advanced options by default so we can actually toggle them

### PR DESCRIPTION
**Pull request by tvb**

### CODE REVIEW

**Comment by tobyzerner** [comment]
This isn't necessary — the advanced options are hidden by JavaScript when the page loads. Is this not happening for you?

**Comment by tvb** [comment]
Nope it did not.

**Comment by tobyzerner** [comment]
Can't reproduce. `$(".advanced").hide();` is definitely being executed on the page and works fine for me.

**Comment by tvb** [comment]
I will try to reproduce this then. It wouldn't hurt to hide it with CSS instead of by JS though?

**Comment by tobyzerner** [comment]
Although it's not quite as relevant as it was three years ago, esoTalk is built to be fully degradable — i.e. when JavaScript is disabled, you can still use it without losing much functionality. Hiding the fields with CSS would remove this degradability.

**Comment by tvb** [comment]
Ah, that does make sense.

**Pull request closed without merging**
