### PR TITLE
add a StopForumSpam Plugin

### PR DESCRIPTION
**Pull request by joshuaruesweg**
add a StopForumSpam Plugin

### CODE REVIEW

**Comment by tvb** [comment]
Thanks!

**Comment by tobyzerner** [comment]
Great work! Rather than being included in the core repo, this plugin should be put in its own repo (e.g. joshuaruesweg/StopForumSpam) and then posted on http://esotalk.org/plugins.

**Comment by joshuaruesweg** [comment]
@tobscure Thanks! But how does it look with the inserted event? Is there a better event, which I can use?

**Comment by joshuaruesweg** [comment]
@tobscure any suggestions?

**Comment by tobyzerner** [comment]
Oops sorry. Pulled 957386a to develop

**Comment by joshuaruesweg** [comment]
Thanks :) 

The plugin is now here: https://github.com/joshuaruesweg/esoTalk-SFS

**Pull request closed without merging**
